# NPC 配置文件描述
header: |-
  RsNPC - NPC配置文件
  警告！编辑此文件前请确认您已掌握YAML语法！
  您可以从这里学习YAML
  https://www.runoob.com/w3cnote/yaml-intro.html
footer: |-
  你已经到达配置文件的底部啦

ConfigVersion: |-
  -
  -
  配置文件的版本号
  警告！ 除非您明确知道您在干什么，否则不要尝试改动此项配置！

name: "NPC的显示名称（头顶名称）"
坐标: "NPC的坐标"
手持: "手持物品id 例如267:0 为空则不显示"
头部: "头部护甲的物品id 例如298:0 为空则不显示"
胸部: "胸部护甲的物品id 例如299:0 为空则不显示"
腿部: "腿部护甲的物品id 例如300:0 为空则不显示"
脚部: "脚步护甲的物品id 例如301:0 为空则不显示"
皮肤: "使用的皮肤名称"
实体NetworkId: |-
  发包显示给玩家时所用的实体NetworkId
  实体ID介绍请参考：https://minecraft.fandom.com/zh/wiki/%E5%9F%BA%E5%B2%A9%E7%89%88%E6%95%B0%E6%8D%AE%E5%80%BC/%E5%AE%9E%E4%BD%93ID
  无特殊需求请设置为 -1 使用假玩家实体
实体大小: "实体大小"
看向玩家: "是否看向玩家"
表情动作.启用: "NPC是否播放表情"
表情动作.表情ID: |-
  已知的表情ID：https://github.com/lt-name/GetEmoteID/blob/master/README.md
  请注意！此配置为List类型！
  格式：
   - "ID1"
   - "ID2"
表情动作.间隔: "NPC播放表情的间隔 单位：秒"
允许抛射物触发: "是否允许抛射物触发 例如箭 雪球等"
点击执行指令: |-
  点击NPC执行的指令
  请注意！此配置为List类型！
  格式：
   - "命令1&权限"
   - "命令2&权限"
  &前为命令，&后为权限 权限不写默认玩家权限
  &con 使用控制台权限执行命令
  &op 使用op权限执行命令
  例如:
   - "give @p 260 1&con"
   - "say @p 你好&con"
发送消息: |-
  点击NPC发送的消息
  请注意！此配置为List类型！
  格式：
   - "消息1"
   - "消息2"
  例如：
   - "%npcName%： @p 您好"
   - "送您一个苹果！"
基础移动速度: "npc移动的速度"
route: "路径列表 请使用命令添加！"
启用辅助寻路: |-
  辅助寻路功能
  启用后NPC自动绕过障碍物向目标点移动 （地形会变情况下推荐使用）
  不启用NPC忽视障碍物直接向目标点移动 （地形不变情况下省性能使用）
旋转: |-
  NPC的旋转角度 设置为负数可以反向旋转
  可用于旋转展示皮肤
  开启此项会自动关闭NPC移动
对话框.启用: "是否启用对话框"
对话框.页面: "对话框配置文件名称"
CustomEntity.enable: "是否启用自定义实体"
CustomEntity.identifier: "自定义实体标识符（资源包内设置的identifier）"