# 对话框 配置文件描述
header: |-
  RsNPC - 对话框配置文件
footer: |-
  你已经到达配置文件的底部啦

defaultPage: "默认打开的页面，填写下方pages中的key"
pages: |- 
  页面 格式：
  - key: "1" #页面的key
    title: "演示对话框" #页面标题
    content: "这是一个演示对话框" #页面内容
    buttons: #按钮
      - text: "关闭" #按钮显示名称
        action: "close" #此项留空默认关闭对话框
        cmd: #执行命令
          - "me hello" #玩家权限执行命令
          - "say hello @p&op" #op权限执行命令
          - "tell @p 这是一个测试命令&con" #控制台权限执行命令
      - text: "下一页" #按钮显示名称
        go: "2" #前往其他页面 填写其他页面的key